insert into public.internships (
  title,
  organization,
  country,
  city,
  internship_type,
  degree_level,
  duration,
  funding,
  deadline,
  official_url,
  description,
  logo_url,
  featured
) values
(
  'UNICEF Internship Programme',
  'UNICEF',
  'Global',
  'Multiple locations and remote options',
  'Humanitarian',
  'Undergraduate, Graduate, PhD, Recent graduates',
  '6 to 26 weeks; full-time or part-time depending on office needs',
  'Paid monthly stipend; travel and visa contribution may be available when funding allows',
  'Rolling - opportunities open throughout the year',
  'https://www.unicef.org/careers/internships',
  'UNICEF offers students and recent graduates practical experience in the humanitarian and development sector through internship opportunities across offices worldwide. Applicants should be at least 18 and enrolled in or recently graduated from an undergraduate, graduate, or PhD program.',
  '',
  true
),
(
  'AIESEC Global Talent',
  'AIESEC',
  'Global',
  'Multiple host countries',
  'Professional',
  'Undergraduate, Graduate, Recent graduates',
  'Varies by host organization and internship listing',
  'Varies by opportunity; many placements include local support and practical workplace experience',
  'Rolling - depends on selected opportunity',
  'https://aiesec.org/global-talent',
  'AIESEC Global Talent connects young people with international professional internships across business, technology, marketing, engineering, finance, and other fields. The program emphasizes cross-cultural workplace experience and leadership development.',
  '',
  true
),
(
  'Max Planck Research Internship',
  'Max Planck Society - Computer and Information Science',
  'Germany',
  'Multiple Max Planck institutes',
  'Research',
  'Undergraduate, Graduate, Master''s',
  'Varies by research group and project',
  'Funding varies by institute, project, and host group; applicants should confirm support details before applying',
  'Application portal availability varies',
  'https://apply.cis.mpg.de/register/internship',
  'The Max Planck Society Computer and Information Science application system supports internship registration for research opportunities connected to Max Planck institutes. Applicants create an account and follow the portal process for available internship projects.',
  '',
  false
),
(
  'Max Planck School Matter to Life URO',
  'Max Planck School Matter to Life',
  'Germany',
  'Labs across the Matter to Life network',
  'Research',
  'Undergraduate',
  '10 weeks',
  'Fully funded support for travel, accommodation, and living expenses',
  'Next application cycle to be announced - check official website',
  'https://mattertolife.maxplanckschools.org/uro-research-internship',
  'The Matter to Life Undergraduate Research Opportunities program offers bachelor''s students a funded 10-week research internship with faculty fellows in Germany, focused on interdisciplinary life sciences and research training.',
  '',
  true
),
(
  'DAAD RISE Professional',
  'DAAD / Research in Germany',
  'Germany',
  'German companies and non-university research institutions',
  'Industry Research',
  'Master''s, PhD, RISE Germany alumni',
  '3 months, with 10 weeks minimum, up to 6 months',
  'Monthly scholarship of 861 euros for bachelor''s/master''s students and 1,200 euros for PhD students; travel expenses and insurance support included',
  'Annual application cycle - check official website',
  'https://www.research-in-germany.org/research-funding/funding-programmes/daad-rise-professional-summer-internships-with-german-companies.html',
  'RISE Professional offers research internships in Germany for eligible students from the USA, Canada, the United Kingdom, or Ireland who want practical science and engineering experience with German companies or industry-linked research institutions.',
  '',
  true
)
on conflict (title, organization) do nothing;
