-- Add AI-generated content columns to opportunities table
-- These columns will store content generated by Google Gemini API

alter table public.opportunities 
  add column if not exists ai_generated_description text,
  add column if not exists seo_title text,
  add column if not exists seo_description text,
  add column if not exists tags text[],
  add column if not exists ai_content_generated_at timestamptz,
  add column if not exists is_ai_content_generated boolean default false;

-- Add index for filtering by AI-generated content
create index if not exists opportunities_ai_generated_idx on public.opportunities (is_ai_content_generated);

-- Add comment to document the new columns
comment on column public.opportunities.ai_generated_description is 'AI-generated professional description using Gemini API';
comment on column public.opportunities.seo_title is 'AI-generated SEO-optimized title';
comment on column public.opportunities.seo_description is 'AI-generated SEO meta description';
comment on column public.opportunities.tags is 'AI-generated relevant tags for categorization';
comment on column public.opportunities.ai_content_generated_at is 'Timestamp when AI content was generated';
comment on column public.opportunities.is_ai_content_generated is 'Flag indicating if AI content has been generated';
